export enum UserRole {
  STORAGE_CUSTOMER = 'STORAGE_CUSTOMER',
  FACILITY_STAFF = 'FACILITY_STAFF',
  FACILITY_MANAGER = 'FACILITY_MANAGER',
  BUSINESS_OPERATIONS_MANAGER = 'BUSINESS_OPERATIONS_MANAGER',
  SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR',
}
